# Generated by Django 5.2.7 on 2025-12-07 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning_logs", "0004_remove_entry_owner_topic_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="entry",
            name="hours_spent",
            field=models.DecimalField(
                decimal_places=1,
                default=0,
                help_text="Hours spent studying for this entry (e.g., 0.5, 1.0, 2.5).",
                max_digits=4,
            ),
        ),
        migrations.AddField(
            model_name="entry",
            name="study_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="entry",
            name="study_location",
            field=models.CharField(
                choices=[
                    ("home", "Home"),
                    ("library", "Library"),
                    ("work", "Work"),
                    ("classroom", "Classroom"),
                    ("coffee", "Coffee shop"),
                    ("other", "Other"),
                ],
                default="home",
                max_length=50,
            ),
        ),
    ]
